[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stopwaitsecs=3600

[program:horizon]
command=php /var/www/html/artisan horizon
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/horizon.log
stderr_logfile=/var/log/supervisor/horizon_err.log
user=www-data
stopasgroup=true
killasgroup=true

# php artisan queue:work --queue=default,email,sms --tries=3   /in order of priority ie:only these queues will be processed for single worker

# In Case of High-Traffic Application with Multiple Queues
# [program:queue-default]
# command=php /var/www/html/artisan queue:work --queue=default --tries=3
# autostart=true
# autorestart=true
# user=www-data
# numprocs=2
# stdout_logfile=/var/www/html/storage/logs/queue-default.log
# stderr_logfile=/var/www/html/storage/logs/queue-default.err.log

# [program:queue-emails]
# command=php /var/www/html/artisan queue:work --queue=emails --tries=3
# autostart=true
# autorestart=true
# user=www-data
# numprocs=4  # More workers for emails if needed
# stdout_logfile=/var/www/html/storage/logs/queue-emails.log
# stderr_logfile=/var/www/html/storage/logs/queue-emails.err.log

# [program:queue-sms]
# command=php /var/www/html/artisan queue:work --queue=sms --tries=3
# autostart=true
# autorestart=true
# user=www-data
# numprocs=1  # Fewer workers for SMS if it's less busy
# stdout_logfile=/var/www/html/storage/logs/queue-sms.log
# stderr_logfile=/var/www/html/storage/logs/queue-sms.err.log